### ISSUE TITLE
beds not separated into mbr container in hierarchy view

### ISSUE THREAD

**Issue by cambro** [UW-Macrostrat/sift#18]
When beds are present in, for example a member in a formation, the beds plot at same rank as bed and are not nested.

e.g., https://dev.macrostrat.org/sift/info/?strat_id=13752

**Comment by jczaplew** [comment]
@cambro  is this still an issue?

**Comment by cambro** [comment]
I'm not sure here. the original link no longer works and I can't find that strat_name_id, which is odd....

**Comment by jczaplew** [comment]
Closing this since it can't be confirmed.
