### ISSUE TITLE
Add map toggle controls

### ISSUE THREAD

**Issue by cambro** [UW-Macrostrat/sift#23]
It would be useful in some cases to be able to go to satellite base map. particularly when in burwell mode

**Comment by jczaplew** [comment]
Toggle should be similar to that in Burwell. Include buttons for fossils, satellite, and bedrock.

**Comment by jczaplew** [comment]
Routes to implement this on:

- [ ] `column`
- [ ] `strat_name`
- [ ] `strat_name_concept`
