### ISSUE TITLE
definitions pages: fields to include and sorting

### ISSUE THREAD

**Issue by cambro** [UW-Macrostrat/sift#34]
**intervals**: interval_type
**stratigraphic names**: include containing interval or interval from strat_names_meta? 
**lithologies**: include synonyms when replacing name (e.g., dolostone = dolomite), order by class, then by type, then by name
**environments**: order by class, then by type, then by name
**economics**: order by class, then by type, then by name

**Comment by jczaplew** [comment]
Need to fix this fix to close this issue - https://github.com/UW-Macrostrat/macrostrat-api/issues/114

**Comment by jczaplew** [comment]
A containing interval name will not be included for stratigraphic names as outlined here - https://github.com/UW-Macrostrat/macrostrat-api/issues/114#issuecomment-152226734
