### ISSUE TITLE
formation not shown in hierarchy when selected (fm->sgp)

### ISSUE THREAD

**Issue by cambro** [UW-Macrostrat/sift#46]
https://macrostrat.org/sift/#/strat_name/9583
but present here in parent selection:
https://macrostrat.org/sift/#/strat_name/10111

**Comment by cambro** [comment]
note that i updated this name, but the potential problem is still present

**Comment by jczaplew** [comment]
Definitely a UI problem because these requests both return Keele - https://macrostrat.org/api/v2/defs/strat_names?rule=all&strat_name_id=9583 and https://macrostrat.org/api/v2/defs/strat_names?rule=all&strat_name_id=10111
