### ISSUE TITLE
radical statistics misreporting on /columns: everything very wrong (units, packages, area, thickness, pbdb_matches)

### ISSUE THREAD

**Issue by cambro** [UW-Macrostrat/sift#55]
https://macrostrat.org/sift/#/column/298

This reports 361 units and 83 packages. The data service response is just fine and reports correct t_units=28 and t_sections=7:
https://macrostrat.org/api/v2/columns?col_id=298&response=long&adjacents=true&format=topojson

So this is some kind of interface/interpretation weirdness that I can't track down.

**Comment by cambro** [comment]
Update: every single stat is radically misreported and not even close to what is reported in the data service call.

**Comment by jczaplew** [comment]
Fixed with 01ecd4dbc87739f646
