### ISSUE TITLE
error in concept view

### ISSUE THREAD

**Issue by cambro** [UW-Macrostrat/sift#64]
https://macrostrat.org/api/v2/columns?strat_name_concept_id=15019&response=long&format=topojson

```"name": "error",
"length": 172,
"severity": "ERROR",
"code": "42703",
"hint": "Perhaps you meant to reference the column \"cols.col_name\".",
"position": "247",
"file": "parse_relation.c",
"line": "3293",
"routine": "errorMissingColumn"
```

**Comment by cambro** [comment]
@jczaplew this is new behavior and problem almost certainly something done during recent updates.

**Comment by jczaplew** [comment]
Fixed with `macrostrat schlep cols` on strata
